version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: dental-mongodb
    environment:
      MONGO_INITDB_DATABASE: dentaldb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./docker-data:/data/db
    ports:
      - 27017:27017