export const REASONS = [
	'Necesito un chequeo dental para mantener mi salud bucal en óptimas condiciones.',
	'Tengo dolor de muelas y necesito que un dentista revise y trate el problema.',
	'Mis encías están inflamadas y sangran al cepillarme, necesito un diagnóstico y tratamiento adecuado.',
	'He notado que mis dientes están desalineados y quiero explorar opciones de ortodoncia.',
	'Quiero realizarme una limpieza dental profesional para eliminar la placa y el sarro acumulados.',
	'Me gustaría blanquear mis dientes para mejorar mi sonrisa y aumentar mi confianza.',
	'Uno de mis empastes dentales se ha caído y necesito que sea reparado lo antes posible.',
	'Sufro de apnea del sueño y quiero explorar opciones de tratamiento como los dispositivos orales.',
	'Tengo problemas de mordida y quiero consultar a un ortodoncista para obtener un diagnóstico y plan de tratamiento.',
	'He notado la aparición de úlceras bucales frecuentes y necesito una evaluación y recomendaciones para su manejo.',
];

export const CANCEL_REASONS = [
	'Emergencia médica',
	'Conflicto de horario',
	'Enfermedad repentina',
	'Imposibilidad de asistir',
	'Cambio de planes',
	'Cita reprogramada',
	'Otro compromiso urgente',
	'Motivos personales',
	'Problemas de transporte',
	'Falta de disponibilidad',
	'Decisión del paciente',
	'Inconvenientes laborales',
	'Imposibilidad de asistencia',
	'Cambio en la situación',
	'Enfermedad familiar',
	'Pérdida de interés',
	'Problemas de salud',
	'Olvido de la cita',
	'Imprevisto de último momento',
	'Demora en el trabajo',
];
